sudo: required
language: c
before-install:
- sudo apt-get install -y --force-yes flex bison git qemu-kvm git-remote-google
script:
  - set -e
  - set +x
  - cd $AKAROS_ROOT
  - (cd $AKAROS_ROOT && make ARCH=x86 defconfig)
  - (cd $AKAROS_ROOT && travis_wait 80 ./travis.sh)
  - (cd $AKAROS_ROOT && make apps-install)
  - (cd $AKAROS_ROOT && make fill-kfs)
  - (cd $AKAROS_ROOT && make)
  - echo "Build SUCCESS"
env:
  global:
  - ARCH=x86
  - AKAROS_ROOT=$TRAVIS_BUILD_DIR
  - X86_64_INSTDIR="$AKAROS_ROOT/install/x86_64-ucb-akaros-gcc"
  - PATH=$X86_64_INSTDIR/bin:$PATH
  - AKAROS_XCC_ROOT=$X86_64_INSTDIR
  - MAKE_JOBS=4
